### ISSUE TITLE
useDeviceOrientation screen bug

### ISSUE THREAD

**Issue by xuqianjin** [react-native-community/hooks#202]
# Bug report

## Environment info

`react-native info` output:

```bash
# "react-native": "^0.63.2",
```

Library version: ^2.6.0

orientation.landscape is always false when change orientation

**Comment by vicm159** [comment]
I have the same issue was working fine until i upgrade to RN 0.63. We previously had RN version 0.62.2

**Comment by xuqianjin** [comment]
> I have the same issue was working fine until i upgrade to RN 0.63. We previously had RN version 0.62.2

that seems a RN bug not the hooks

**Comment by carolinex** [comment]
I can confirm that Dimensions are not updating on orientation change in RN 0.63, with or without use of useDeviceOrientation hook. If you downgrade to 0.62.2 it works as intended.

**Comment by NateRedding** [comment]
I hit this issue too. Looks like this hook is using the 'screen' dimensions. I was able to work around it by making my own hook based on the 'window' dimensions.

**Comment by shahiran12395** [comment]
Hi, I have issue with useDeviceOrientation() it does not return current orientation of my device and android emulator. How can i fix it?

**Comment by SorinGabriel02** [comment]
The fastest fix is to use `useDimentions` hook instead:
```
const { height, width } = useDimensions().window;
const landscape = width > height;
```

**Comment by hausos** [comment]
Thanks for the input!

> The fastest fix is to use `useDimentions` hook instead:
> 
> ```
> const { height, width } = useDimensions().window;
> const landscape = width > height;
> ```

**Comment by montagnev** [comment]
hello, I'll have a time next week to work on this, I'll try to fix `useDeviceOrientation` hook

**Comment by LinusU** [comment]
@montagnev thank you for testing this! ❤️

**Comment by Taro-Naza** [comment]
> I just tested with the version `2.8.1` of the library and version `0.67.4` of react-native and it works fine.

I'm using the version `2.8.1` and it is not working for me.
