### ISSUE TITLE
RN 0.65.1 + useKeyboard() + Fast Refresh = react-native not available on the unmount

### ISSUE THREAD

**Issue by aforty** [react-native-community/hooks#247]
I just upgraded to RN 0.65.1 and didn't have this problem before but this is also the only library I'm having this issue with.

When I change something in the file and Fast Refresh reloads the file I get the following error where it appears that upon reload `react-native` is no longer loaded on the unmount in `node_modules/@react-native-community/hooks/lib/useKeyboard.js`.

![Screen Shot 2021-08-26 at 11 52 53](https://user-images.githubusercontent.com/523683/130995837-8bb05a1f-b336-44ae-8e63-ae72b3c7d5ff.png)

**Comment by yulolimum** [comment]
@aforty 
I was looking for a hook for the keyboard status and ran into this lib. However, you're right in the fact that the current implementation is out-dated.

`Keyboard.removeListener()` is deprecated: https://reactnative.dev/docs/keyboard#removelistener

It is used all over here: https://github.com/react-native-community/hooks/blob/master/src/useKeyboard.ts#L51-L54

You can either `patch-package` or contribute to this repo with this code (which seems to fix the issue): 

```
  useEffect(() => {
    const keyboardWillShow = Keyboard.addListener("keyboardWillShow", handleKeyboardWillShow)
    const keyboardDidShow = Keyboard.addListener("keyboardDidShow", handleKeyboardDidShow)
    const keyboardWillHide = Keyboard.addListener("keyboardWillHide", handleKeyboardWillHide)
    const keyboardDidHide = Keyboard.addListener("keyboardDidHide", handleKeyboardDidHide)

    return () => {
      keyboardWillShow.remove()
      keyboardDidShow.remove()
      keyboardWillHide.remove()
      keyboardDidHide.remove()
    }
  }, [])
```
