### ISSUE TITLE
涉及前端源码泄露，可以删除不？

### ISSUE THREAD

**Issue by Rattenking** [react-native-community/hooks#343]
大佬，删除一个库：https://github.com/ke2933/demo
我们公司查代码，涉及前端源码泄露，可以删除不？

**Comment by LinusU** [comment]
Unfortunately I don't understand this language, you'll have to post in english/swedish for me to help you 😅

**Comment by Rattenking** [comment]
我看了，没有这个库




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "react-native-community/hooks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月23日(星期二) 中午12:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [react-native-community/hooks] 涉及前端源码泄露，可以删除不？ (Issue #343)





 
Closed #343 as completed.
