### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by PhilippeCollin** [react-native-community/hooks#46]
Hi, it seems like no license is attached to this repo yet. This would imply exclusive copyright by default, as stated [here](https://choosealicense.com/no-permission/).

Assuming this is just an oversight, a license should probably be added to avoid any doubt that this repo is open source.

**Comment by pvinis** [comment]
There is the license (here)[https://github.com/react-native-community/react-native-hooks/blob/master/package.json#L15], but I might as well add it as a file.

**Comment by pvinis** [comment]
Addressed in https://github.com/react-native-community/react-native-hooks/pull/57.

**Comment by PhilippeCollin** [comment]
My bad, it didn't occur to me to look there. Thanks anyway for the change!
